project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('funfact/', include('story7.urls')),
    path('books/', include('story8.urls')),
    path('', include('story10.urls')),
]

story10/urls.py
from django.urls import path, include
from .views import login_page, register,logout_page, welcome

app_name = "story10"

urlpatterns = [
    path('', login_page, name='login'),
    path('register/', register, name='register'),
    path('logout/', logout_page, name='logout'),
    path('welcome/', welcome, name='welcome'),
]

story7/urls.py
from django.urls import path
from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.funfact, name='funfact'),
]

story8/urls.py
from django.urls import path, include
from .views import books, fungsi_data

app_name = "story8"

urlpatterns = [
    path('', books, name='books'),
    path('data/', fungsi_data, name = "fungsi_data"),
]

story10/models.py
from django.db import models

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story10/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class' : 'form-control',
            'type' : 'text',
            'required' : True,
            'autocomplete' : 'off',
        }
    ))
    password = forms.CharField(widget=forms.TextInput(
        attrs={
            'class' : 'form-control',
            'type' : 'password',
            'required' : True,
            'autocomplete' : 'off',
        }
    ))


class RegisterForm(forms.Form):
    email = forms.CharField(widget=forms.TextInput(
        attrs={
            'class' : 'form-control',
            'type' : 'email',
            'required' : True,
            'autocomplete' : 'off',
        }
    ))
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class' : 'form-control',
            'type' : 'text',
            'required' : True,
            'autocomplete' : 'off',
        }
    ))

    password = forms.CharField(widget=forms.TextInput(
        attrs={
            'class' : 'form-control',
            'type' : 'password',
            'required' : True,
            'autocomplete' : 'off',
        }
    ))

story10/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from .forms import LoginForm, RegisterForm

# Create your views here
def login_page(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            input_username = form.cleaned_data["username"]
            input_password = form.cleaned_data["password"]
            user = authenticate(request, username = input_username, password = input_password)
            if user is not None:
                login(request, user)
                return redirect('story10:welcome')
    form = LoginForm()
    response = {
        "form" : form,        
    }
    return render(request, "login.html", response)

@login_required(login_url='/')
def logout_page(request):
    logout(request)
    return redirect("story10:login")

def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if (form.is_valid()):
            input_email = form.cleaned_data["email"]
            input_username = form.cleaned_data["username"]
            input_password = form.cleaned_data["password"]
            try:
                user_temp = User.objects.get(username = input_username)
                return redirect("story10:login")
            except User.DoesNotExist:
                user_temp = User.objects.create_user(input_username, input_email, input_password)
                return redirect("story10:login")
    form = RegisterForm()
    response = {
        "form" : form
    }
    return render(request, "register.html", response)

@login_required
def welcome(request):
    return render(request, 'welcome.html')

story7/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='/')
def funfact(request):
    return render(request, 'funfact.html')

story8/views.py
from django.shortcuts import render, HttpResponse
from django.http import JsonResponse
import urllib.request, json
import requests
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url="/")
def books(request):
    response = {}
    return render(request, 'books.html', response)
@login_required(login_url="/")
def fungsi_data(request):
    url = "https://www.googleapis.com/books/v1/volumes?q="+ request.GET['q']
    res = requests.get(url)
    data = json.loads(res.content)
    return JsonResponse(data)

story10/templates/login.html
{% extends 'base.html' %}
{%load static%}

{% block extra_headers %}

  <link rel="stylesheet" href= "{% static './login/login.css' %}">

{% endblock extra_headers %}

{% block content %}
<h3> Login </h3>
<form method="POST">
    {% csrf_token %}
        {{ form }}
    <br>
    <button type="submit" class="btn btn-secondary"> Login </button>
            <br>
            <br>
        <h6> Doesn't have an account? <a href="{% url 'story10:register' %}">Register</a></h6>
</form>



{% endblock %}

story10/templates/register.html
{% extends 'base.html' %}
{%load static%}

{% block extra_headers %}

  <link rel="stylesheet" href= "{% static './login/login.css' %}">

{% endblock extra_headers %}

{% block content %}
<h3> Create Account </h3>
    <form method="POST">
            {% csrf_token %}
              {{ form }}
        <br>
    <button type="submit" class="btn btn-secondary"> Create </button>
            <br>
            <br>
        <h6>Already have an account? <a href="{% url 'story10:login' %}">Login</a></h6>
    </form>


 </form>

{% endblock %}

story10/templates/welcome.html
{% extends 'base.html' %}
{%load static%}

{% block extra_headers %}

  <link rel="stylesheet" href= "{% static './login/login.css' %}">

{% endblock extra_headers %}

{% block content%}
<div class="container">
<br>
<br>
<br>
    <h2> Welcome {{ user.username }}</h2>
  </div>
</div>
{% endblock %}

story7/templates/funfact.html
{% extends 'base.html' %}
{%load static%}

{% block extra_headers %}

  <link rel="stylesheet" href= "{% static './funfact/funfact.css' %}">

{% endblock extra_headers %}

{% block content %}

  <button class="accordion" >
    Favorite Food 
    <a class="up"> ^ </a>
    <a class="down"> V </a>
  </button>
  <div class="panel">
      <li> Fried Chicken </li>
      <li> Fettuchini </li>
  </div>
<button class="accordion"> 
    Activities     
    <a class="up"> ^ </a>
    <a class="down"> V </a>
  </button>
  <div class = "panel">
    <ul>
        <li> Code </li>
        <li> Eat </li>
        <li> Cry </li>
        <li> Sleep </li>
        <li> Laugh </li>
        <li> Repeat </li>
    </ul>
  </div>
<button class="accordion"> 
  Experiences 
  <a class="up"> ^ </a>
  <a class="down"> V </a>
</button>
  <div class="panel"> 
    <ul>
        <li> Staff Of Playground COMPFEST 12 </li>
        <li> Staff of Sport Departmen BEM Fasikom UI 2020 </li>
        <li> Liaison Officer at Online Young Lead Summit </li>
        <li> Volunteer at Panda Mobile WWF Indonesia </li>
        <li> Vice Person in Charge Liaison Officer Open House Fasilkom UI 2020</li>
        <li> Staff of Event Wisuda Ganjil Fasilkom UI 2019</li>
        <li> Staff of Futsal Planner PERAK Fasilkom UI 2019</li> 
    </ul>
  </div>

<button class="accordion"> 
  Achievement 
    <a class="up"> ^ </a>
    <a class="down"> V </a>
  </button>
  <div class="panel">
    :)
  </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script type="text/javascript" src="{% static './funfact/funfact.js' %}"> </script>
{% endblock %}

story8/templates/books.html
{% extends 'base.html' %}
{%load static%}

{% block extra_headers %}

  <link rel="stylesheet" href= "{% static './books/books.css' %}">

{% endblock extra_headers %}

{% block content %}
<div class="my-container black-background bg-changed1">
    <h1> Books </h1>
    <form autocomplete="off" class="src-form" action="#">
        <input type="text" placeholder="Book title" id="user-input">
    </form>
    <br>
    <table class="table table-responsive-lg">
        <thead>
        <tr>
            <th>Image</th>
            <th>Title</th>
            <th>Author</th>
            <th> Publisher </th>
            <th> Preview </th>
        </tr>
        </thead>
        <tbody id='result'>
    
        </tbody>
    </table>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static './books/books.js' %}"></script>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title> Raniah Nur Hanami </title>
  <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@400;700&display=swap" rel="stylesheet">

  <!-- Bootstrap -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

  <!-- CSS -->
  <link rel="stylesheet" href="{% static 'style.css' %}">

    <!-- Custom Headers -->
  {% block extra_headers %}
  {% endblock %}
</head>
<body> 
    {% if request.user.is_authenticated %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#menu" aria-controls="navbarTogglerDemo02" aria-expanded="true" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="menu">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'story7:funfact' %}">Funfact</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'story8:books' %}">Books</a>
                </li>
            </ul>
            <a class="nav-link" href="{% url 'story10:logout' %}">Logout</a>
        </div>
    </nav>

    {% else %}
        <br>
        <br>
        <h2> Hello There! </h2>
    {% endif %}
    {% block content %}
    {% endblock %}
</body>
<html>